--- Hammerspoon clipboard manager, the mechanism. Composition root.
---
--- A self-contained clipboard history that lives entirely in Lua, no companion
--- app. It polls the pasteboard, records text, urls, images, and files, shows a
--- searchable hs.chooser with a live preview pane docked beside it, and pastes
--- the chosen item back into the frontmost app.
---
--- This is the mechanism only. It knows nothing about being a provider; it just
--- exposes an API, configure, start, show, isShowing, and clear. The contract
--- face that plugs it into the ClipboardHistory chain lives outside it, in
--- providers/hammerspoon.lua, which delegates to this API. This file is the only
--- one that names the concrete internal pieces. It loads the siblings by absolute
--- path (a spoon dir is not on package.path), holds the config defaults, and
--- wires store, readers, monitor, and ui together.
---
--- Responsibilities split across the folder:
---   util.lua     pure string and pasteboard helpers
---   store.lua    history list, persistence, image and file media lifecycle
---   readers.lua  per-type capture readers, a Chain of Responsibility
---   monitor.lua  the poll engine and paste-back, owns the self-capture guard
---   ui.lua       the chooser and the live preview pane

-- Load siblings by absolute path, the same idiom Capture.spoon uses.
local spoonPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
local function load(name)
  local chunk, err = loadfile(spoonPath .. name)
  if not chunk then
    error("clipboard native: failed to load " .. name .. ": " .. tostring(err))
  end
  return chunk()
end

local util = load("util.lua")
local store = load("store.lua")
local readers = load("readers.lua")
local monitor = load("monitor.lua")
local ui = load("ui.lua")

local HOME = os.getenv("HOME")
local DATA_DIR = HOME .. "/.cache/hs-clipboard"

-- hs.chooser sizes by whole row count, not pixels, and it clamps its own height
-- to fit the screen below where it opens, so rows(N) is only a request. The ui
-- reads the chooser's real rendered frame after it shows and sizes the preview
-- to match, so both panes are always the same height regardless of clamping. The
-- fitted line (42pt per row over a 201pt search-field and chrome base) is kept
-- only to seed the preview's first frame before that correction. 19 rows asks
-- for about 1000pt, used in full where the screen has room. Fractional counts are
-- rejected by hs.chooser, so this must stay a whole number.
local CHOOSER_ROWS = 19 -- 201 + 19*42 = 999pt requested height
local CHOOSER_ROW_H = 42 -- measured points per visible row
local CHOOSER_BASE_H = 201 -- measured search-field and chrome overhead, points

-- Defaults. The outer composition root may override any of these via configure()
-- before start(). Stored outside the git-tracked config dir.
local config = {
  cacheParent = HOME .. "/.cache",
  dataDir = DATA_DIR,
  thumbDir = DATA_DIR .. "/thumbs",
  filesDir = DATA_DIR .. "/files",
  storePath = DATA_DIR .. "/history.json",

  maxEntries = 1000, -- history cap, trimmed on insert
  maxFileSnapshot = 50 * 1024 * 1024, -- do not snapshot files larger than this
  thumbEdge = 64, -- row thumbnail box, points
  previewEdge = 1200, -- downscaled preview image box, points
  fileReadCap = 256 * 1024, -- how much of a text file to preview

  pollInterval = 0.5, -- changeCount poll
  pasteDelay = 0.1, -- focus settle before Cmd+V
  previewPoll = 0.08, -- follow-selection poll

  chooserWidthPct = 32, -- list width, percent of screen
  paneMaxW = 500, -- cap for each pane's width, in points
  chooserRows = CHOOSER_ROWS, -- desired row count, trimmed on short screens to keep the padding
  chooserRowH = CHOOSER_ROW_H, -- points per row, used to fit rows to the screen
  chooserBaseH = CHOOSER_BASE_H, -- search-field and chrome overhead, points
  previewW = 500,
  previewH = CHOOSER_BASE_H + CHOOSER_ROWS * CHOOSER_ROW_H, -- seed height, matchPreviewToChooser corrects it
  uiGap = 12,
  uiTopFrac = 0.06, -- bias the pair toward the top of the screen
  minVPad = 60, -- mandatory space above and below the pair, honored on short screens

  -- NSPasteboard hints that a copy must not be recorded; the concealed one is
  -- what password managers stamp.
  skipTypes = {
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
  },
}

local function merged(extra)
  local t = {}
  for k, v in pairs(config) do t[k] = v end
  for k, v in pairs(extra) do t[k] = v end
  return t
end

local M = {}

--- M.show() - reveal the clipboard chooser with its live preview pane.
function M.show()
  ui.show()
end

--- M.isShowing() - is the chooser currently visible.
function M.isShowing()
  return ui.isShowing()
end

--- M.hide() - dismiss the chooser and its preview pane.
function M.hide()
  ui.hide()
end

--- M.clear() - wipe history and media. Handy from the console:
--- hs -c "spoon.ClipboardHistory.providers.hammerspoon.clear()"
function M.clear()
  store.clear()
  ui.refresh()
end

--- M.configure(opts) - override any config default before start.
function M.configure(opts)
  if opts then
    for k, v in pairs(opts) do
      config[k] = v
    end
  end
  return M
end

--- M.start() - wire the pieces and begin monitoring. Called once by the outer
--- composition root. Safe across hs.reload(): reload tears down the whole Lua
--- state and history is read back from disk here.
function M.start()
  math.randomseed(os.time())
  config.util = util

  store.configure(config)
  monitor.configure({
    readers = readers.build(util),
    store = store,
    util = util,
    skipTypes = config.skipTypes,
    pollInterval = config.pollInterval,
    pasteDelay = config.pasteDelay,
  })
  ui.configure(merged({ store = store, monitor = monitor, util = util }))

  store.load()
  ui.build()
  monitor.start()
  return M
end

return M
