#!/bin/bash
set -e

# Install every runtime the mise module lists and this machine lacks.
#
# Runs after stow, since the list is the stowed ~/.config/mise/config.toml. It installs what is
# absent and never moves a version already present, which is the rule for this whole layer.
# Run from the home directory so a project's own mise.toml in the caller's directory cannot add
# to what a setup run installs.

if ! command -v mise >/dev/null 2>&1; then
    echo "Error: mise not found. It is declared by the mise module and mapped in DEPENDENCIES.map."
    exit 1
fi

if [[ ! -f "$HOME/.config/mise/config.toml" ]]; then
    echo "Error: ~/.config/mise/config.toml is missing. Stow the mise package first."
    exit 1
fi

# Which tool groups this machine takes comes from MACHINES, and mise learns it from miserc.toml,
# the one file it reads before any config, where `env` loads config.<group>.toml for each group.
# The file is generated, ignored by git, and rewritten on every run, so changing the row and
# running this step again is the whole of moving a machine between groups.
CONFIG_DIR="$HOME/.config/mise"
groups="$("$(dirname "${BASH_SOURCE[0]}")/machine.sh" get tools)"
if [[ "$groups" == "none" ]]; then
    rm -f "$CONFIG_DIR/miserc.toml"
    echo "No tool groups for this machine, runtimes only"
else
    list=""
    IFS=',' read -r -a wanted <<< "$groups"
    for group in "${wanted[@]}"; do
        if [[ ! -f "$CONFIG_DIR/config.$group.toml" ]]; then
            echo "Error: MACHINES names the tool group $group and there is no config.$group.toml in the mise package."
            exit 1
        fi
        list="$list${list:+, }\"$group\""
    done
    printf '# Generated by src/install-mise-tools.sh from MACHINES, never edited by hand.\nenv = [%s]\n' "$list" > "$CONFIG_DIR/miserc.toml"
    echo "Tool groups for this machine, $groups"
fi

echo "Installing mise runtimes and tools..."

cd "$HOME"
mise install

echo "mise runtimes present"
mise ls --current
