#!/bin/bash
set -e

# Give this machine the mise tools its MACHINES row picks, and install whichever are missing.
#
# Two inputs and one output. dotfiles/mise/TOOLS defines every tool once with its version, and
# knows nothing about machines. The tools row in MACHINES names what this machine takes, and
# knows nothing about versions. This step is the only place that joins them, and it writes
# ~/.config/mise/conf.d/machine.toml, which mise loads beside the stowed config.toml. The file is
# rewritten on every run, so changing the row or the catalog and running this again is the whole
# of changing a machine. It installs what is absent and never moves a version already present.
# Run from the home directory so a project's own mise.toml in the caller's directory cannot add
# to what a setup run installs.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"
CATALOG="$ROOT/dotfiles/mise/TOOLS"
CONFIG_DIR="$HOME/.config/mise"
OUT="$CONFIG_DIR/conf.d/machine.toml"

if ! command -v mise >/dev/null 2>&1; then
    echo "Error: mise not found. It is declared by the mise module and mapped in DEPENDENCIES.map."
    exit 1
fi

if [[ ! -f "$CONFIG_DIR/config.toml" ]]; then
    echo "Error: ~/.config/mise/config.toml is missing. Stow the mise package first."
    exit 1
fi

machine="$("$SCRIPT_DIR/machine.sh" name)"
picked="$("$SCRIPT_DIR/machine.sh" get tools)"
[[ "$picked" == "none" ]] && picked=""

# The catalog as name|tool|version, comments and padding removed.
catalog="$(awk -F'|' '
    { sub(/#.*/, "") }
    NF < 3 { next }
    { for (i = 1; i <= 3; i++) gsub(/^[ \t]+|[ \t]+$/, "", $i); print $1 "|" $2 "|" $3 }
' "$CATALOG")"

unknown=""
IFS=',' read -r -a names <<< "$picked"
for name in ${names[@]+"${names[@]}"}; do
    awk -F'|' -v n="$name" '$1 == n { found = 1 } END { exit !found }' <<< "$catalog" ||
        unknown="$unknown $name"
done
if [[ -n "$unknown" ]]; then
    echo "Error: MACHINES picks${unknown} for $machine, and dotfiles/mise/TOOLS defines no such tool."
    exit 1
fi

# Picked rows in catalog order, merged by mise tool, so several python rows become one list with
# the first as the default. Every key is quoted, since a backend name carries a colon.
tools="$(awk -F'|' -v picked=",$picked," '
    index(picked, "," $1 ",") == 0 { next }
    !($2 in versions) { order[++n] = $2; versions[$2] = "\"" $3 "\""; count[$2] = 1; next }
    { versions[$2] = versions[$2] ", \"" $3 "\""; count[$2]++ }
    END {
        for (i = 1; i <= n; i++) {
            t = order[i]
            v = count[t] > 1 ? "[" versions[t] "]" : versions[t]
            print "\"" t "\" = " v
        }
    }
' <<< "$catalog")"

mkdir -p "$CONFIG_DIR/conf.d"
{
    echo "# Generated by src/install-mise-tools.sh for $machine from MACHINES and dotfiles/mise/TOOLS."
    echo "# Never edit it. Change the row or the catalog and run the step again."
    echo "[tools]"
    [[ -n "$tools" ]] && echo "$tools"
} > "$OUT"

# The tool groups this replaced were chosen through miserc.toml, so a machine set up before the
# catalog still has one, and it would keep loading group files that no longer exist.
rm -f "$CONFIG_DIR/miserc.toml"

if [[ -z "$picked" ]]; then
    echo "No mise tools picked for $machine, wrote an empty tool list"
    exit 0
fi

echo "Installing mise tools for $machine, $picked"
cd "$HOME"
mise install

echo "mise tools present"
mise ls --current
